package com.wao.digitalsignpdf.ui;

import com.wao.digitalpdf.callback.UploadFileCallBack;
import com.wao.digitalsignpdf.CreateSignature;
import com.wao.digitalsignpdf.api.response.Bill;
import com.wao.digitalsignpdf.utils.UploadFile;
import com.wao.digitalsignpdf.utils.Utils;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;

/**
 *
 * @author BaoBang
 */
public class PanelKeyStoreList extends javax.swing.JPanel {

    private List<String> aliases;
    private final FrameMain frame;

    private final ActionListener nextActionListener;
    private final ActionListener previousActionListener;
    private File[] oldListRoot = File.listRoots();

    private int totalOrders = 0;
    private int countOrders = 1;
    String error = "";

    /**
     * Creates new form PanelKeyStoreList
     *
     * @param frame
     */
    public PanelKeyStoreList(FrameMain frame) {
        initComponents();
        this.frame = frame;
        getAliases();
        previousActionListener = (e) -> {
            doClickPrevious();
        };
        nextActionListener = (e) -> {
            doClickNext();
        };
        waitForNotifying();
    }

    private void waitForNotifying() {
        Thread t = new Thread(() -> {
            while (true) {
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                }
                if (File.listRoots().length > oldListRoot.length) {
                    oldListRoot = File.listRoots();
                    try {
                        Thread.sleep(3000);
                    } catch (InterruptedException ex) {
                    }
                    getAliases();
                } else if (File.listRoots().length < oldListRoot.length) {
                    oldListRoot = File.listRoots();
                    getAliases();
                }

            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listKeyStores = new javax.swing.JList<>();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                onPanleAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        listKeyStores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Chọn chữ kí số", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        listKeyStores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listKeyStores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Phương thức được gọi khi panel này được add vào một component khác.
     */

    private void onPanleAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_onPanleAdded
        // TODO add your handling code here:
        getAliases();
        frame.setTextButtonNext("Chọn");
        frame.setNextButton(nextActionListener, true);
        frame.setPreviousButton(previousActionListener, true);
    }//GEN-LAST:event_onPanleAdded

    /**
     * Phương thức được gọi khi người dùng click vào button previous Remove
     * listener của button next và button previous
     */
    private void doClickPrevious() {
        frame.removeListener(previousActionListener, nextActionListener);
        frame.previousStep();
        frame.attachPanel();
    }

    /**
     * phương thức được gọi khi người dùng click vào button next Kiểm tra hợp lệ
     * input Thực hiện sign pdf
     */
    private void doClickNext() {
        if (listKeyStores.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(frame, "Vui lòng chọn chữ kí số");
            return;
        }
        try {
            String alias = aliases.get(listKeyStores.getSelectedIndex());
            List<Bill> orders = frame.getPanelListOrder().getOrderSelected();
            totalOrders = orders.size();
            countOrders = 0;
            error = "";
            // load the keystore
            KeyStore keystore = KeyStore.getInstance("Windows-MY");

            keystore.load(null, null);
            java.awt.EventQueue.invokeLater(() -> {
                frame.showLoading(null);
            });

            for (Bill b : orders) {
                // sign PDF
                CreateSignature signing = new CreateSignature(keystore, alias, "123456781".toCharArray());
                signing.setExternalSigning(true);
                File inFile = Utils.getFileFromURL(b.getLink());
             
                UploadFile file = new UploadFile(signing, frame.getAPIService(), inFile, new UploadFileCallBack() {
                    @Override
                    public void onSuccess() {
                        increaseOrderUploaded();
                        checkUploadedSuccess();
                    }

                    @Override
                    public void onFailed(String message) {
                        error = error + message + "\r\n";
                        increaseOrderUploaded();
                        checkUploadedSuccess();
                    }
                });
                file.start();
            }

        } catch (KeyStoreException | IOException | NoSuchAlgorithmException | CertificateException | UnrecoverableKeyException ex) {
            Logger.getLogger(PanelKeyStoreList.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void increaseOrderUploaded() {
        countOrders++;
    }

    public void checkUploadedSuccess() {
        if (countOrders == totalOrders) {
            java.awt.EventQueue.invokeLater(() -> {
                frame.hideLoading();
            });
            if (error.equals("")) {
                JOptionPane.showMessageDialog(frame, "Đăng kí thành công");
            }else{
                JOptionPane.showMessageDialog(frame, error);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listKeyStores;
    // End of variables declaration//GEN-END:variables

    private void getAliases() {
        aliases = Utils.getKeystores();
        DefaultListModel<String> model = new DefaultListModel<>();
        model.clear();
        for (String alias : aliases) {
            model.addElement(alias);
        }
        listKeyStores.setModel(model);
    }

}
